---
- name: Install chrony daemon
  ansible.builtin.yum:
    name: chrony
    state: latest

- name: Set up default default chrony server
  ansible.builtin.lineinfile:
    dest: /etc/chrony.conf
    regexp: ^server
    insertafter: "^#server "
    line: server ntp.hpc iburst

- name: Restart chronyd daemon
  ansible.builtin.service:
    name: chronyd
    enabled: true
    state: restarted
